/**
 * Destrieux (aparc.a2009s) source names in standard French anatomical nomenclature
 * (Terminologia Anatomica / neuroanatomie française), with French navigation lobes.
 */
export const DESTRIEUX_LABELS_FR = {
  'G_and_S_frontomargin': { name: 'Gyrus et sillon fronto-marginaux', lobe: 'Frontal' },
  'G_and_S_occipital_inf': { name: 'Gyrus et sillon occipitaux inférieurs', lobe: 'Occipital' },
  'G_and_S_paracentral': { name: 'Lobule et sillon paracentraux', lobe: 'Central' },
  'G_and_S_subcentral': { name: 'Gyrus et sillons sous-centraux', lobe: 'Central' },
  'G_and_S_transv_frontopol': { name: 'Gyri et sillons fronto-polaires transverses', lobe: 'Frontal' },
  'G_and_S_cingul-Ant': { name: 'Gyrus et sillon cingulaires antérieurs', lobe: 'Cingulaire' },
  'G_and_S_cingul-Mid-Ant': { name: 'Gyrus et sillon cingulaires moyens-antérieurs', lobe: 'Cingulaire' },
  'G_and_S_cingul-Mid-Post': { name: 'Gyrus et sillon cingulaires moyens-postérieurs', lobe: 'Cingulaire' },
  'G_cingul-Post-dorsal': { name: 'Gyrus cingulaire postéro-dorsal', lobe: 'Cingulaire' },
  'G_cingul-Post-ventral': { name: 'Gyrus cingulaire postéro-ventral', lobe: 'Cingulaire' },
  'G_cuneus': { name: 'Cunéus', lobe: 'Occipital' },
  'G_front_inf-Opercular': { name: 'Partie operculaire du gyrus frontal inférieur', lobe: 'Frontal', aliases: ['GFI', 'pars opercularis', 'Broca', 'IFG'] },
  'G_front_inf-Orbital': { name: 'Partie orbitaire du gyrus frontal inférieur', lobe: 'Frontal', aliases: ['GFI', 'pars orbitalis', 'IFG'] },
  'G_front_inf-Triangul': { name: 'Partie triangulaire du gyrus frontal inférieur', lobe: 'Frontal', aliases: ['GFI', 'pars triangularis', 'Broca', 'IFG'] },
  'G_front_middle': { name: 'Gyrus frontal moyen', lobe: 'Frontal', aliases: ['GFM', 'MFG'] },
  'G_front_sup': { name: 'Gyrus frontal supérieur', lobe: 'Frontal', aliases: ['GFS', 'SFG'] },
  'G_Ins_lg_and_S_cent_ins': { name: 'Gyrus long de l’insula et sillon central de l’insula', lobe: 'Insula' },
  'G_insular_short': { name: 'Gyri courts de l’insula', lobe: 'Insula' },
  'G_occipital_middle': { name: 'Gyrus occipital moyen', lobe: 'Occipital' },
  'G_occipital_sup': { name: 'Gyrus occipital supérieur', lobe: 'Occipital' },
  'G_oc-temp_lat-fusifor': { name: 'Gyrus occipito-temporal latéral (fusiforme)', lobe: 'Temporal', aliases: ['fusiforme', 'fusiform'] },
  'G_oc-temp_med-Lingual': { name: 'Gyrus lingual', lobe: 'Occipital' },
  'G_oc-temp_med-Parahip': { name: 'Gyrus parahippocampique', lobe: 'Limbique' },
  'G_orbital': { name: 'Gyri orbitaires', lobe: 'Frontal' },
  'G_pariet_inf-Angular': { name: 'Gyrus angulaire', lobe: 'Pariétal' },
  'G_pariet_inf-Supramar': { name: 'Gyrus supramarginal', lobe: 'Pariétal' },
  'G_parietal_sup': { name: 'Lobule pariétal supérieur', lobe: 'Pariétal' },
  'G_postcentral': { name: 'Gyrus postcentral', lobe: 'Pariétal', aliases: ['S1'] },
  'G_precentral': { name: 'Gyrus précentral', lobe: 'Frontal', aliases: ['M1'] },
  'G_precuneus': { name: 'Précunéus', lobe: 'Pariétal' },
  'G_rectus': { name: 'Gyrus droit', lobe: 'Frontal', aliases: ['gyrus rectus'] },
  'G_subcallosal': { name: 'Aire sous-calleuse', lobe: 'Limbique' },
  'G_temp_sup-G_T_transv': { name: 'Gyrus temporal transverse (Heschl)', lobe: 'Temporal', aliases: ['Heschl'] },
  'G_temp_sup-Lateral': { name: 'Face latérale du gyrus temporal supérieur', lobe: 'Temporal', aliases: ['GTS', 'STG'] },
  'G_temp_sup-Plan_polar': { name: 'Planum polare', lobe: 'Temporal' },
  'G_temp_sup-Plan_tempo': { name: 'Planum temporale', lobe: 'Temporal' },
  'G_temporal_inf': { name: 'Gyrus temporal inférieur', lobe: 'Temporal', aliases: ['GTI', 'ITG'] },
  'G_temporal_middle': { name: 'Gyrus temporal moyen', lobe: 'Temporal', aliases: ['GTM', 'MTG'] },
  'Lat_Fis-ant-Horizont': { name: 'Rameau horizontal du sillon latéral', lobe: 'Scissure latérale' },
  'Lat_Fis-ant-Vertical': { name: 'Rameau vertical du sillon latéral', lobe: 'Scissure latérale' },
  'Lat_Fis-post': { name: 'Rameau postérieur du sillon latéral', lobe: 'Scissure latérale', aliases: ['Sylvius', 'scissure de Sylvius', 'Sylvian'] },
  'Pole_occipital': { name: 'Pôle occipital', lobe: 'Occipital' },
  'Pole_temporal': { name: 'Pôle temporal', lobe: 'Temporal' },
  'S_calcarine': { name: 'Sillon calcarin', lobe: 'Occipital' },
  'S_central': { name: 'Sillon central', lobe: 'Central', aliases: ['Rolando', 'scissure de Rolando', 'Rolandic'] },
  'S_cingul-Marginalis': { name: 'Branche marginale du sillon cingulaire', lobe: 'Cingulaire' },
  'S_circular_insula_ant': { name: 'Segment antérieur du sillon circulaire de l’insula', lobe: 'Insula' },
  'S_circular_insula_inf': { name: 'Segment inférieur du sillon circulaire de l’insula', lobe: 'Insula' },
  'S_circular_insula_sup': { name: 'Segment supérieur du sillon circulaire de l’insula', lobe: 'Insula' },
  'S_collat_transv_ant': { name: 'Sillon collatéral transverse antérieur', lobe: 'Temporal' },
  'S_collat_transv_post': { name: 'Sillon collatéral transverse postérieur', lobe: 'Occipital' },
  'S_front_inf': { name: 'Sillon frontal inférieur', lobe: 'Frontal' },
  'S_front_middle': { name: 'Sillon frontal moyen', lobe: 'Frontal' },
  'S_front_sup': { name: 'Sillon frontal supérieur', lobe: 'Frontal' },
  'S_interm_prim-Jensen': { name: 'Sillon intermédiaire primus de Jensen', lobe: 'Pariétal' },
  'S_intrapariet_and_P_trans': { name: 'Sillons intrapariétal et pariétaux transverses', lobe: 'Pariétal', aliases: ['SIP', 'IPS'] },
  'S_oc-temp_lat': { name: 'Sillon occipito-temporal latéral', lobe: 'Temporal' },
  'S_oc-temp_med_and_Lingual': { name: 'Sillons occipito-temporal médial et lingual', lobe: 'Occipital' },
  'S_oc_middle_and_Lunatus': { name: 'Sillons occipital moyen et lunaire', lobe: 'Occipital' },
  'S_oc_sup_and_transversal': { name: 'Sillons occipital supérieur et transverse', lobe: 'Occipital' },
  'S_occipital_ant': { name: 'Sillon occipital antérieur', lobe: 'Occipital' },
  'S_orbital-H_Shaped': { name: 'Sillons orbitaires en H', lobe: 'Frontal' },
  'S_orbital_lateral': { name: 'Sillon orbitaire latéral', lobe: 'Frontal' },
  'S_orbital_med-olfact': { name: 'Sillon orbitaire médial (olfactif)', lobe: 'Frontal' },
  'S_parieto_occipital': { name: 'Sillon pariéto-occipital', lobe: 'Occipital' },
  'S_pericallosal': { name: 'Sillon péricalleux', lobe: 'Cingulaire' },
  'S_postcentral': { name: 'Sillon postcentral', lobe: 'Pariétal' },
  'S_precentral-inf-part': { name: 'Partie inférieure du sillon précentral', lobe: 'Frontal' },
  'S_precentral-sup-part': { name: 'Partie supérieure du sillon précentral', lobe: 'Frontal' },
  'S_suborbital': { name: 'Sillon sous-orbitaire', lobe: 'Frontal' },
  'S_subparietal': { name: 'Sillon sous-pariétal', lobe: 'Pariétal' },
  'S_temporal_inf': { name: 'Sillon temporal inférieur', lobe: 'Temporal' },
  'S_temporal_sup': { name: 'Sillon temporal supérieur', lobe: 'Temporal' },
  'S_temporal_transverse': { name: 'Sillon temporal transverse', lobe: 'Temporal' },
};
