/**
 * Destrieux (aparc.a2009s) source names, their published anatomical names, and
 * a lobe for navigation.
 *
 * The lobe is a navigation aid, not a measured boundary: several of these
 * regions straddle a lobar border by definition, and the perirolandic entries
 * are grouped as "Central" rather than forced into frontal or parietal.
 * `aliases` are alternative names people search by. They are nomenclature, not
 * functional claims, so no entry maps an anatomical structure onto a
 * functional area.
 */
export const DESTRIEUX_LABELS = {
  'G_and_S_frontomargin': { name: 'Frontomarginal gyrus and sulcus', lobe: 'Frontal' },
  'G_and_S_occipital_inf': { name: 'Inferior occipital gyrus and sulcus', lobe: 'Occipital' },
  'G_and_S_paracentral': { name: 'Paracentral lobule and sulcus', lobe: 'Central' },
  'G_and_S_subcentral': { name: 'Subcentral gyrus and sulci', lobe: 'Central' },
  'G_and_S_transv_frontopol': { name: 'Transverse frontopolar gyri and sulci', lobe: 'Frontal' },
  'G_and_S_cingul-Ant': { name: 'Anterior cingulate gyrus and sulcus', lobe: 'Cingulate' },
  'G_and_S_cingul-Mid-Ant': { name: 'Middle-anterior cingulate gyrus and sulcus', lobe: 'Cingulate' },
  'G_and_S_cingul-Mid-Post': { name: 'Middle-posterior cingulate gyrus and sulcus', lobe: 'Cingulate' },
  'G_cingul-Post-dorsal': { name: 'Posterior-dorsal cingulate gyrus', lobe: 'Cingulate' },
  'G_cingul-Post-ventral': { name: 'Posterior-ventral cingulate gyrus', lobe: 'Cingulate' },
  'G_cuneus': { name: 'Cuneus', lobe: 'Occipital' },
  'G_front_inf-Opercular': { name: 'Opercular part of the inferior frontal gyrus', lobe: 'Frontal', aliases: ['IFG', 'pars opercularis', 'Broca'] },
  'G_front_inf-Orbital': { name: 'Orbital part of the inferior frontal gyrus', lobe: 'Frontal', aliases: ['IFG', 'pars orbitalis'] },
  'G_front_inf-Triangul': { name: 'Triangular part of the inferior frontal gyrus', lobe: 'Frontal', aliases: ['IFG', 'pars triangularis', 'Broca'] },
  'G_front_middle': { name: 'Middle frontal gyrus', lobe: 'Frontal', aliases: ['MFG'] },
  'G_front_sup': { name: 'Superior frontal gyrus', lobe: 'Frontal', aliases: ['SFG'] },
  'G_Ins_lg_and_S_cent_ins': { name: 'Long insular gyrus and central insular sulcus', lobe: 'Insula' },
  'G_insular_short': { name: 'Short insular gyri', lobe: 'Insula' },
  'G_occipital_middle': { name: 'Middle occipital gyrus', lobe: 'Occipital' },
  'G_occipital_sup': { name: 'Superior occipital gyrus', lobe: 'Occipital' },
  'G_oc-temp_lat-fusifor': { name: 'Lateral occipitotemporal (fusiform) gyrus', lobe: 'Temporal', aliases: ['fusiform'] },
  'G_oc-temp_med-Lingual': { name: 'Lingual gyrus', lobe: 'Occipital' },
  'G_oc-temp_med-Parahip': { name: 'Parahippocampal gyrus', lobe: 'Limbic' },
  'G_orbital': { name: 'Orbital gyri', lobe: 'Frontal' },
  'G_pariet_inf-Angular': { name: 'Angular gyrus', lobe: 'Parietal' },
  'G_pariet_inf-Supramar': { name: 'Supramarginal gyrus', lobe: 'Parietal' },
  'G_parietal_sup': { name: 'Superior parietal lobule', lobe: 'Parietal' },
  'G_postcentral': { name: 'Postcentral gyrus', lobe: 'Parietal', aliases: ['S1'] },
  'G_precentral': { name: 'Precentral gyrus', lobe: 'Frontal', aliases: ['M1'] },
  'G_precuneus': { name: 'Precuneus', lobe: 'Parietal' },
  'G_rectus': { name: 'Straight gyrus', lobe: 'Frontal', aliases: ['gyrus rectus'] },
  'G_subcallosal': { name: 'Subcallosal area', lobe: 'Limbic' },
  'G_temp_sup-G_T_transv': { name: 'Transverse temporal gyrus (Heschl)', lobe: 'Temporal', aliases: ['Heschl'] },
  'G_temp_sup-Lateral': { name: 'Lateral aspect of the superior temporal gyrus', lobe: 'Temporal', aliases: ['STG'] },
  'G_temp_sup-Plan_polar': { name: 'Planum polare', lobe: 'Temporal' },
  'G_temp_sup-Plan_tempo': { name: 'Planum temporale', lobe: 'Temporal' },
  'G_temporal_inf': { name: 'Inferior temporal gyrus', lobe: 'Temporal', aliases: ['ITG'] },
  'G_temporal_middle': { name: 'Middle temporal gyrus', lobe: 'Temporal', aliases: ['MTG'] },
  'Lat_Fis-ant-Horizont': { name: 'Horizontal ramus of the anterior lateral fissure', lobe: 'Lateral fissure' },
  'Lat_Fis-ant-Vertical': { name: 'Vertical ramus of the anterior lateral fissure', lobe: 'Lateral fissure' },
  'Lat_Fis-post': { name: 'Posterior ramus of the lateral fissure', lobe: 'Lateral fissure', aliases: ['Sylvian'] },
  'Pole_occipital': { name: 'Occipital pole', lobe: 'Occipital' },
  'Pole_temporal': { name: 'Temporal pole', lobe: 'Temporal' },
  'S_calcarine': { name: 'Calcarine sulcus', lobe: 'Occipital' },
  'S_central': { name: 'Central sulcus', lobe: 'Central', aliases: ['Rolandic'] },
  'S_cingul-Marginalis': { name: 'Marginal branch of the cingulate sulcus', lobe: 'Cingulate' },
  'S_circular_insula_ant': { name: 'Anterior segment of the circular insular sulcus', lobe: 'Insula' },
  'S_circular_insula_inf': { name: 'Inferior segment of the circular insular sulcus', lobe: 'Insula' },
  'S_circular_insula_sup': { name: 'Superior segment of the circular insular sulcus', lobe: 'Insula' },
  'S_collat_transv_ant': { name: 'Anterior transverse collateral sulcus', lobe: 'Temporal' },
  'S_collat_transv_post': { name: 'Posterior transverse collateral sulcus', lobe: 'Occipital' },
  'S_front_inf': { name: 'Inferior frontal sulcus', lobe: 'Frontal' },
  'S_front_middle': { name: 'Middle frontal sulcus', lobe: 'Frontal' },
  'S_front_sup': { name: 'Superior frontal sulcus', lobe: 'Frontal' },
  'S_interm_prim-Jensen': { name: 'Intermediate primus sulcus of Jensen', lobe: 'Parietal' },
  'S_intrapariet_and_P_trans': { name: 'Intraparietal and transverse parietal sulci', lobe: 'Parietal', aliases: ['IPS'] },
  'S_oc-temp_lat': { name: 'Lateral occipitotemporal sulcus', lobe: 'Temporal' },
  'S_oc-temp_med_and_Lingual': { name: 'Medial occipitotemporal and lingual sulci', lobe: 'Occipital' },
  'S_oc_middle_and_Lunatus': { name: 'Middle occipital and lunate sulci', lobe: 'Occipital' },
  'S_oc_sup_and_transversal': { name: 'Superior and transverse occipital sulci', lobe: 'Occipital' },
  'S_occipital_ant': { name: 'Anterior occipital sulcus', lobe: 'Occipital' },
  'S_orbital-H_Shaped': { name: 'Orbital H-shaped sulci', lobe: 'Frontal' },
  'S_orbital_lateral': { name: 'Lateral orbital sulcus', lobe: 'Frontal' },
  'S_orbital_med-olfact': { name: 'Medial orbital (olfactory) sulcus', lobe: 'Frontal' },
  'S_parieto_occipital': { name: 'Parieto-occipital sulcus', lobe: 'Occipital' },
  'S_pericallosal': { name: 'Pericallosal sulcus', lobe: 'Cingulate' },
  'S_postcentral': { name: 'Postcentral sulcus', lobe: 'Parietal' },
  'S_precentral-inf-part': { name: 'Inferior part of the precentral sulcus', lobe: 'Frontal' },
  'S_precentral-sup-part': { name: 'Superior part of the precentral sulcus', lobe: 'Frontal' },
  'S_suborbital': { name: 'Suborbital sulcus', lobe: 'Frontal' },
  'S_subparietal': { name: 'Subparietal sulcus', lobe: 'Parietal' },
  'S_temporal_inf': { name: 'Inferior temporal sulcus', lobe: 'Temporal' },
  'S_temporal_sup': { name: 'Superior temporal sulcus', lobe: 'Temporal' },
  'S_temporal_transverse': { name: 'Transverse temporal sulcus', lobe: 'Temporal' },
};
