/**
 * NextBrain structures in French anatomical nomenclature.
 *
 * Keyed by `source_name`: the published name with its laterality prefix and its
 * vestigial `ctx-rh-` fragment removed, so one entry serves both hemispheres.
 *
 * Entries are added as they are verified. Anything absent falls back to the
 * published English name rather than an invented translation, so this table can
 * be incomplete without being wrong — the same reason HCP-MMP areas keep their
 * published codes. `group` overrides the alphabetical bucket a name would
 * otherwise be filed under.
 */
export const NEXTBRAIN_LABELS_FR = {
  // --- Cortex (Desikan-Killiany parcellation) ---
  bankssts: { name: 'Berges du sillon temporal supérieur', group: 'Temporal' },
  caudalanteriorcingulate: { name: 'Gyrus cingulaire antérieur caudal', group: 'Cingulaire' },
  caudalmiddlefrontal: { name: 'Gyrus frontal moyen caudal', group: 'Frontal' },
  cuneus: { name: 'Cunéus', group: 'Occipital' },
  entorhinal: { name: 'Cortex entorhinal', group: 'Temporal' },
  frontalpole: { name: 'Pôle frontal', group: 'Frontal' },
  fusiform: { name: 'Gyrus fusiforme', group: 'Temporal', aliases: ['fusiforme'] },
  inferiorparietal: { name: 'Cortex pariétal inférieur', group: 'Pariétal' },
  inferiortemporal: { name: 'Gyrus temporal inférieur', group: 'Temporal' },
  insula: { name: 'Insula', group: 'Insula' },
  isthmuscingulate: { name: 'Isthme du gyrus cingulaire', group: 'Cingulaire' },
  lateraloccipital: { name: 'Cortex occipital latéral', group: 'Occipital' },
  lateralorbitofrontal: { name: 'Cortex orbito-frontal latéral', group: 'Frontal' },
  lingual: { name: 'Gyrus lingual', group: 'Occipital' },
  medialorbitofrontal: { name: 'Cortex orbito-frontal médial', group: 'Frontal' },
  middletemporal: { name: 'Gyrus temporal moyen', group: 'Temporal' },
  paracentral: { name: 'Lobule paracentral', group: 'Frontal' },
  parahippocampal: { name: 'Gyrus parahippocampique', group: 'Temporal' },
  parsopercularis: { name: 'Partie operculaire du gyrus frontal inférieur', group: 'Frontal', aliases: ['GFI', 'pars opercularis'] },
  parsorbitalis: { name: 'Partie orbitaire du gyrus frontal inférieur', group: 'Frontal', aliases: ['GFI', 'pars orbitalis'] },
  parstriangularis: { name: 'Partie triangulaire du gyrus frontal inférieur', group: 'Frontal', aliases: ['GFI', 'pars triangularis'] },
  pericalcarine: { name: 'Cortex péricalcarin', group: 'Occipital' },
  postcentral: { name: 'Gyrus postcentral', group: 'Pariétal', aliases: ['S1'] },
  posteriorcingulate: { name: 'Gyrus cingulaire postérieur', group: 'Cingulaire' },
  precentral: { name: 'Gyrus précentral', group: 'Frontal', aliases: ['M1'] },
  precuneus: { name: 'Précunéus', group: 'Pariétal' },
  rostralanteriorcingulate: { name: 'Gyrus cingulaire antérieur rostral', group: 'Cingulaire' },
  rostralmiddlefrontal: { name: 'Gyrus frontal moyen rostral', group: 'Frontal' },
  superiorfrontal: { name: 'Gyrus frontal supérieur', group: 'Frontal' },
  superiorparietal: { name: 'Lobule pariétal supérieur', group: 'Pariétal' },
  superiortemporal: { name: 'Gyrus temporal supérieur', group: 'Temporal' },
  supramarginal: { name: 'Gyrus supramarginal', group: 'Pariétal' },
  temporalpole: { name: 'Pôle temporal', group: 'Temporal' },
  transversetemporal: { name: 'Gyrus temporal transverse', group: 'Temporal', aliases: ['Heschl'] },

  // --- Grandes divisions encéphaliques & voies blanches ---
  'midbrain_(mesencephalon)': { name: 'Mésencéphale', group: 'Tronc cérébral' },
  pons: { name: 'Pont', group: 'Tronc cérébral' },
  'myelencephalon_(medulla_oblongata)': { name: 'Moelle allongée', group: 'Tronc cérébral' },
  anterior_commissure: { name: 'Commissure antérieure', group: 'Substance blanche' },
  optic_chiasm: { name: 'Chiasma optique', group: 'Voies visuelles' },
  optic_tract: { name: 'Tractus optique', group: 'Voies visuelles' },
  fornix: { name: 'Fornix', group: 'Substance blanche' },
  fimbria: { name: 'Fimbria de l’hippocampe', group: 'Substance blanche' },
  septum_pellucidum: { name: 'Septum pellucidum', group: 'Substance blanche' },
  pineal_body: { name: 'Corps pinéal', group: 'Diencéphale' },
  stria_terminalis: { name: 'Strie terminale', group: 'Substance blanche' },
  stria_medullaris_of_thalamus: { name: 'Strie médullaire du thalamus', group: 'Substance blanche' },
  mammillothalamic_tract: { name: 'Faisceau mammillo-thalamique', group: 'Substance blanche' },
  white_matter_of_forebrain: { name: 'Substance blanche du prosencéphale', group: 'Substance blanche' },
  white_matter_of_hindbrain: { name: 'Substance blanche du rhombencéphale', group: 'Substance blanche' },
  white_matter_of_the_cerebellum: { name: 'Substance blanche cérébelleuse', group: 'Cervelet' },
  inferior_cerebellar_peduncle: { name: 'Pédoncule cérébelleux inférieur', group: 'Tronc cérébral' },
  'superior_cerebellar_peduncle_(brachium_conjunctivum)': { name: 'Pédoncule cérébelleux supérieur', group: 'Tronc cérébral' },
  lenticular_fasciculus: { name: 'Fascicule lenticulaire', group: 'Substance blanche' },
  thalamic_fasciculus: { name: 'Fascicule thalamique', group: 'Substance blanche' },
  'fasciculus_retroflexus_(habenuno-interpeduncular_tract)': { name: 'Fascicule rétroflexe', group: 'Substance blanche' },
  inferior_thalamic_peduncle: { name: 'Pédoncule thalamique inférieur', group: 'Substance blanche' },
  mammillary_peduncle: { name: 'Pédoncule mammillaire', group: 'Substance blanche' },
  medial_corticohypothalamic_tract: { name: 'Tractus cortico-hypothalamique médial', group: 'Substance blanche' },

  // --- Ganglions de la base & tronc cérébral ---
  putamen: { name: 'Putamen', group: 'Ganglions de la base' },
  posteroventral_putamen: { name: 'Putamen postéro-ventral', group: 'Ganglions de la base' },
  head_of_caudate: { name: 'Tête du noyau caudé', group: 'Ganglions de la base' },
  body_of_caudate: { name: 'Corps du noyau caudé', group: 'Ganglions de la base' },
  tail_of_caudate: { name: 'Queue du noyau caudé', group: 'Ganglions de la base' },
  external_segment_of_globus_pallidus: { name: 'Segment externe du globus pallidus', group: 'Ganglions de la base' },
  internal_segment_of_globus_pallidus: { name: 'Segment interne du globus pallidus', group: 'Ganglions de la base' },
  ventral_pallidus: { name: 'Pallidum ventral', group: 'Ganglions de la base' },
  core_of_nucleus_accumbens: { name: 'Centre du noyau accumbens', group: 'Ganglions de la base' },
  claustrum: { name: 'Claustrum', group: 'Ganglions de la base' },
  temporal_claustrum: { name: 'Claustrum temporal', group: 'Ganglions de la base' },
  substantia_nigra__compact_part: { name: 'Substance noire, partie compacte', group: 'Tronc cérébral' },
  substantia_nigra__reticular_part: { name: 'Substance noire, partie réticulée', group: 'Tronc cérébral' },
  substantia_innominata: { name: 'Substance innominée', group: 'Prosencéphale basal' },
  basal_nucleus_of_meynert: { name: 'Noyau basal de Meynert', group: 'Prosencéphale basal' },
  red_nucleus: { name: 'Noyau rouge', group: 'Tronc cérébral' },
  ventral_tegmental_area: { name: 'Aire tegmentale ventrale', group: 'Tronc cérébral' },
  zona_incerta: { name: 'Zone incertaine', group: 'Sous-thalamus' },

  // --- Cervelet ---
  'dentate_(lateral)_nucleus': { name: 'Noyau denté', group: 'Cervelet' },
  'fastigial_(medial)_nucleus': { name: 'Noyau fastigial', group: 'Cervelet' },
  'lateral_interpositus_(emboliform)_nucleus': { name: 'Noyau emboliforme', group: 'Cervelet' },
  'medial_interpositus_(globose)_nucleus': { name: 'Noyau globuleux', group: 'Cervelet' },
  inferior_olive__principal_nucleus: { name: 'Olive inférieure, noyau principal', group: 'Tronc cérébral' },
  pontine_nucleus: { name: 'Noyau du pont', group: 'Tronc cérébral' },
  dorsal_raphe_nucleus: { name: 'Noyau dorsal du raphé', group: 'Tronc cérébral' },
  central_nucleus_of_inferior_colliculus: { name: 'Noyau central du colliculus inférieur', group: 'Tronc cérébral' },
  central_gray_of_medulla_oblongata: { name: 'Substance grise centrale de la moelle allongée', group: 'Tronc cérébral' },

  // --- Thalamus & Métathalamus ---
  thalamus: { name: 'Thalamus', group: 'Thalamus' },
  anterodorsal_nucleus_of_thalamus: { name: 'Noyau antéro-dorsal du thalamus', group: 'Thalamus' },
  anteromedial_nucleus_of_thalamus: { name: 'Noyau antéro-médial du thalamus', group: 'Thalamus' },
  anteroventral_nucleus_of_thalamus: { name: 'Noyau antéro-ventral du thalamus', group: 'Thalamus' },
  central_dorsal_nucleus_of_thalamus: { name: 'Noyau centro-dorsal du thalamus', group: 'Thalamus' },
  central_medial_nucleus_of_thalamus: { name: 'Noyau centro-médial du thalamus', group: 'Thalamus' },
  centromedian_nucleus_of_thalamus: { name: 'Noyau centro-médian du thalamus', group: 'Thalamus' },
  lateral_dorsal_nucleus_of_thalamus: { name: 'Noyau latéro-dorsal du thalamus', group: 'Thalamus' },
  lateral_posterior_nucleus_of_thalamus: { name: 'Noyau latéro-postérieur du thalamus', group: 'Thalamus' },
  posterior_nucleus_of_thalamus: { name: 'Noyau postérieur du thalamus', group: 'Thalamus' },
  reticular_nucleus_of_thalamus: { name: 'Noyau réticulaire du thalamus', group: 'Thalamus' },
  parafascicular_nucleus_of_thalamus: { name: 'Noyau parafasciculaire du thalamus', group: 'Thalamus' },
  paraventricular_nucleus: { name: 'Noyau paraventriculaire du thalamus', group: 'Thalamus' },
  parataenial_nucleus_of_thalamus: { name: 'Noyau parataénial du thalamus', group: 'Thalamus' },
  paracentral_nucleus_of_thalamus: { name: 'Noyau paracentral du thalamus', group: 'Thalamus' },
  'rhomboid_(central)_nucleus_of_thalamus': { name: 'Noyau rhomboïde du thalamus', group: 'Thalamus' },
  'reuniens_nucleus_(medioventral_nucleus)_of_thalamus': { name: 'Noyau reuniens du thalamus', group: 'Thalamus' },
  lateral_habenular_nucleus: { name: 'Noyau habénulaire latéral', group: 'Épithalamus' },
  dorsal_lateral_geniculate_nucleus: { name: 'Corps géniculé latéral, noyau dorsal', group: 'Métathalamus' },
  dorsal_medial_geniculate_nucleus: { name: 'Corps géniculé médial, noyau dorsal', group: 'Métathalamus' },
  pulvinar_of_thalamus: { name: 'Pulvinar du thalamus', group: 'Thalamus' },
  anterior_nucleus_of_pulvinar: { name: 'Noyau antérieur du pulvinar', group: 'Thalamus' },
  inferior_nucleus_of_pulvinar: { name: 'Noyau inférieur du pulvinar', group: 'Thalamus' },
  lateral_nucleus_of_pulvinar: { name: 'Noyau latéral du pulvinar', group: 'Thalamus' },
  medial_nucleus_of_pulvinar: { name: 'Noyau médial du pulvinar', group: 'Thalamus' },
  superficial_pulvinar_nucleus: { name: 'Noyau superficiel du pulvinar', group: 'Thalamus' },
  ventral_posterior_medial_nucleus: { name: 'Noyau ventro-postéro-médial du thalamus', group: 'Thalamus', aliases: ['VPM'] },
  ventral_posterior_inferior_nucleus: { name: 'Noyau ventro-postéro-inférieur du thalamus', group: 'Thalamus', aliases: ['VPI'] },
  ventral_medial_nucleus_of_thalamus: { name: 'Noyau ventro-médial du thalamus', group: 'Thalamus' },
  subparafascicular_nucleus_of_thalamus: { name: 'Noyau subparafasciculaire du thalamus', group: 'Thalamus' },
  periventricular_area_of_thalamus: { name: 'Aire périventriculaire du thalamus', group: 'Thalamus' },
  fasciculosus_nucleus_of_thalamus: { name: 'Noyau fasciculaire du thalamus', group: 'Thalamus' },
  intermediodorsal__nucleus_of_thalamus: { name: 'Noyau intermédio-dorsal du thalamus', group: 'Thalamus' },
  diffuse_pulvinar_nucleus: { name: 'Noyau diffus du pulvinar', group: 'Thalamus' },
  limitans_nucleus: { name: 'Noyau limitant', group: 'Thalamus' },

  // --- Hypothalamus ---
  anterior_hypothalamic_nucleus: { name: 'Noyau hypothalamique antérieur', group: 'Hypothalamus' },
  dorsomedial_hypothalamic_nucleus: { name: 'Noyau hypothalamique dorso-médial', group: 'Hypothalamus' },
  posterior_hypothalamic_nucleus: { name: 'Noyau hypothalamique postérieur', group: 'Hypothalamus' },
  arcuate_nucleus_of_hypothalamus: { name: 'Noyau arqué de l’hypothalamus', group: 'Hypothalamus' },
  paraventricular_nucleus_of_hypothalamus: { name: 'Noyau paraventriculaire de l’hypothalamus', group: 'Hypothalamus' },
  supraoptic_nucleus: { name: 'Noyau supra-optique', group: 'Hypothalamus' },
  supramammillary_nucleus: { name: 'Noyau supra-mammillaire', group: 'Hypothalamus' },
  tuberomammillary_nucleus: { name: 'Noyau tubéro-mammillaire', group: 'Hypothalamus' },
  lateral_mammillary_nucleus: { name: 'Noyau mammillaire latéral', group: 'Hypothalamus' },
  medial_preoptic_nucleus: { name: 'Noyau préoptique médial', group: 'Hypothalamus' },
  median_preoptic_nucleus: { name: 'Noyau préoptique médian', group: 'Hypothalamus' },
  lateral_preoptic_area: { name: 'Aire préoptique latérale', group: 'Hypothalamus' },
  preoptic_region_of_hth: { name: 'Région préoptique de l’hypothalamus', group: 'Hypothalamus' },
  supraoptic_region_of_hth: { name: 'Région supra-optique de l’hypothalamus', group: 'Hypothalamus' },
  lateral_tuberal_nuclei: { name: 'Noyaux tubéraux latéraux', group: 'Hypothalamus' },
  infundibular_stalk: { name: 'Tige infundibulaire', group: 'Hypothalamus' },
  pallidohypothalamic_area: { name: 'Aire pallido-hypothalamique', group: 'Hypothalamus' },
  periventricular_nucleus__supraoptic_portion: { name: 'Noyau périventriculaire (portion supra-optique)', group: 'Hypothalamus' },
  periventricular_nucleus__tuberal_portion: { name: 'Noyau périventriculaire (portion tubérale)', group: 'Hypothalamus' },

  // --- Amygdale & Région olfactive ---
  amygdaloid_complex: { name: 'Complexe amygdalien', group: 'Limbique' },
  anterior_amygdaloid_area: { name: 'Aire amygdalienne antérieure', group: 'Limbique' },
  lateral_nucleus: { name: 'Noyau latéral de l’amygdale', group: 'Limbique' },
  'basolateral_nucleus_(basal_nucleus)': { name: 'Noyau baso-latéral de l’amygdale', group: 'Limbique' },
  anterior_olfactory_nucleus: { name: 'Noyau olfactif antérieur', group: 'Rhinencéphale' },
  lateral_olfactory_stria: { name: 'Strie olfactive latérale', group: 'Rhinencéphale' },
  lateral_olfactory_area: { name: 'Aire olfactive latérale', group: 'Rhinencéphale' },
  diagonal_band: { name: 'Bandelette diagonale de Broca', group: 'Prosencéphale basal' },
  bed_nucleus_of_stria_terminalis: { name: 'Noyau du lit de la strie terminale', group: 'Limbique', aliases: ['BNST'] },

  // --- Hippocampe & Subiculum ---
  alveus: { name: 'Alvéus de l’hippocampe', group: 'Hippocampe' },
  rostral_subiculum: { name: 'Subiculum rostral', group: 'Hippocampe' },
  caudal_subiculum: { name: 'Subiculum caudal', group: 'Hippocampe' },
  uncal_subiculum: { name: 'Subiculum uncal', group: 'Hippocampe' },
};
